BookRealm/ViewModels/Home/IndexPageBooksViewModel.cs
using BookRealm.Data.Models;
using BookRealm.Services.Mapping;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BookRealm.ViewModels.Home
{
    public class IndexPageBooksViewModel:IMapFrom<Book>
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double Rating { get; set; }
        public DateTime? DateOfPublish { get; set; }
        public string CoverUrl { get; set; }
    }
}

BookRealm/ViewModels/Home/IndexViewModel.cs
using AutoMapper;
using BookRealm.Data.Models;
using BookRealm.Services.Mapping;

namespace BookRealm.ViewModels.Home
{
    public class IndexViewModel:IMapFrom<Book>//.IHaveCustomMappings
    {
        public IEnumerable<IndexPageBooksViewModel> RandomBooks { get; set; }=new List<IndexPageBooksViewModel>();

        public int BooksCount { get; set; }

        public int ReviewsCount { get; set; }

        public int AuthorsCount { get; set; }
        public int GenresCount { get; set; }

            

        //public void CreateMappings(IProfileExpression configuration)
        //{
        //    configuration.CreateMap<Book, IndexViewModel>()
        //        .ForMember(x => x.BooksCount, opt =>
        //            opt.MapFrom(x =>
        //                x.books.Count()));
        //}
    }
}

BookRealm/Controllers/BooksController.cs
using BookRealm.Data.Common.Repositories;
using BookRealm.Data.Models;
using BookRealm.Models;
using BookRealm.Services;
using BookRealm.ViewModels.Books;
using BookRealm.ViewModels.Category;
using Microsoft.AspNetCore.Mvc;
using System.Text;

namespace BookRealm.Controllers
{
    public class BooksController:Controller
    {
        private readonly IBookService bookService;
        private readonly IDeletableEntityRepository<Book> bookRepository;

        public BooksController(IBookService bookService, IDeletableEntityRepository<Book>bookRepository )
        {
            this.bookService = bookService;
            this.bookRepository = bookRepository;
        }
        
       
        public IActionResult ByCategory(string categoryName)
        {
            var books = this.bookService.GetByCategory<BookInListViewModel>(categoryName);
            return this.View(books);
        }
        [HttpPost]
        public IActionResult Search(string search,int id=1)
        {
            if (search == null)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 12;
            var books = this.bookService.GetByAuthorName<BookInListViewModel>(search,id,ItemsPerPage);
            if (books == null)
            {
                books = this.bookService.GetByTitle<BookInListViewModel>(search);
            }
            var viewModel = new BookListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                BooksCount = this.bookService.GetCount(),
                Books = books,
            };
            return this.View(viewModel);
           
        }
        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 12;
   
            var viewModel = new BookListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                BooksCount = this.bookService.GetCount(),
                Books = this.bookService.GetAll<BookInListViewModel>(id, ItemsPerPage),
            };
            return this.View(viewModel);
        }
       
        public IActionResult ById(string id)
        {
            var book = this.bookService.GetById<BookViewModel>(id);
            return this.View(book);
        }

        [HttpPost]
        //[Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Delete(string id)
        {
            await this.bookService.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.All));
        }
        public IActionResult Details(string id)
        {
            var book = this.bookService.GetById<BookViewModel>(id);
            return this.View(book);
        }

        //[HttpPost]
        //public async Task<IActionResult> SendToEmail(string id)
        //{
        //    var recipe = this.bookService.GetById<BookInListViewModel>(id);
        //    var html = new StringBuilder();
        //    html.AppendLine($"<h1>{recipe.Title}</h1>");
        //    html.AppendLine($"<h3>{recipe.Authors}</h3>");
        //    html.AppendLine($"<img src=\"{recipe.CoverUrl}\" />");
        //    //await this.emailSender.SendEmailAsync("recepti@recepti.com", "MoiteRecepti", "gerig14198@questza.com", recipe.Name, html.ToString());
        //    return this.RedirectToAction(nameof(this.ById), new { id });
        //}


    }
}

BookRealm/Controllers/HomeController.cs
using BookRealm.Models;
using BookRealm.Services;
using BookRealm.ViewModels.Home;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookRealm.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBookService bookService;
        private readonly ICountService countService;

        public HomeController(ILogger<HomeController> logger,IBookService bookService,ICountService countService)
        {
            _logger = logger;
            this.bookService = bookService;
            this.countService = countService;
        }

        public IActionResult Index()
        {
            var countsDto = this.countService.GetCounts();
            //// var viewModel2 = AutoMapperConfig.MapperInstance.Map<IndexViewModel>(countsDto);
            //// var viewModel = this.mapper.Map<IndexViewModel>(countsDto);
            var viewModel = new IndexViewModel
            {
                BooksCount = countsDto.BooksCount,
                AuthorsCount = countsDto.AuthorsCount,
                ReviewsCount=countsDto.ReviewsCount,
                GenresCount=countsDto.GenresCount,
                RandomBooks = this.bookService.GetRandom<IndexPageBooksViewModel>(12),
            };
            return this.View(viewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookRealm/Views/Home/Old_Index.cshtml
@using BookRealm.Common
@model BookRealm.ViewModels.Home.IndexViewModel
@{
    this.ViewData["Title"] = "Home Page";
}

<div class="text-center row">
    <h1 class="display-4">Welcome to @GlobalConstants.SystemName!</h1>
    <div class="col-md-10">
        <div class="row">
            @foreach (var book in this.Model.RandomBooks)
            {
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="@book.CoverUrl" width="300" img-responsive class="img-fluid rounded-start" alt="@book.Title">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">@book.Title</h5>
                            <p class="card-text">Rating: @book.Rating</p>
                            <p class="card-text">Date of publish: @book.DateOfPublish</p>
                            <p class="card-text">Description: @book.Description.Substring(0,100)...</p>                            
                              
                                <a asp-controller="Books" asp-action="ById" asp-route-id="@book.Id" class="btn btn-primary">Go to details</a>
                            </div>
                        </div>
                    </div>
                </div>
               
            }
        </div>
    </div>
    <div class="col-md-4">
        <p>We have:</p>
        <ul class="list-group">
            <li class="list-group-item bg-info">Books: @Model.BooksCount</li>
            <li class="list-group-item bg-light">Authors: @Model.AuthorsCount</li>
            <li class="list-group-item bg-info">Reviews: @Model.ReviewsCount</li>
            <li class="list-group-item bg-light">Genres: @Model.GenresCount</li>

        </ul>
    </div>
</div>